###################################################################
# Project information
###################################################################
site_name:        ProGuardCORE
site_description: The ProGuardCORE library
site_author:      Guardsquare NV
copyright:        Copyright &copy; 2002-2022 Guardsquare NV

repo_name: guardsquare/proguard-core
repo_url: https://github.com/guardsquare/proguard-core
edit_uri: edit/master/docs/md/

###################################################################
# Options
###################################################################
theme:
  name: material
  logo: img/core.png
  favicon: img/guardsquare.png
  language: en
  palette: blue

docs_dir: md
site_dir: html

extra_css:
  - extra.css

use_directory_urls: false
#strict: true # broken links are errors

###################################################################
# Theme specific
###################################################################
extra:
  #font:
  #  text: 'Droid Sans'
  #  code: 'Ubuntu Mono'
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/Guardsquare/proguard-core
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/guardsquare
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/guardsquare-nv
  - icon: fontawesome/brands/facebook
    link: https://www.facebook.com/guardsquare
  #feature:
  #  tabs: true

###################################################################
# Extensions
###################################################################
markdown_extensions:
- attr_list
- admonition
- codehilite
- footnotes
- def_list
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

###################################################################
# Page tree
###################################################################
nav:
- Introduction:                                 index.md
- Reading classes:                              reading.md
- Creating classes:                             creating.md
- Editing classes:                              editing.md
- Pattern matching:                             patternmatching.md
- Analyzing code:
  - Data flow analysis with partial evaluation: partialevaluator.md
  - Taint analysis with CPA:                    taintcpa.md
- Kotlin metadata:                              kotlin.md
- License:                                      license.md
- Downloads:                                    downloads.md
- Building:                                     building.md
- Release notes:                                releasenotes.md
