name: Continuous Integration
on:
  pull_request:
    branches:
      - master
      - setup-sonar-plugin
  push:
    branches:
      - master
      - setup-sonar-plugin
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Sonar
        run: gradle -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=guardsquare -Dsonar.projectKey=Guardsquare_proguard-core sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.PROGUARD_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.PROGUARD_SONAR_TOKEN }}
