on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
name: Sonar
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PROGUARD_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.PROGUARD_SONAR_TOKEN }}
        with:
          projectBaseDir: src/